### PR TITLE
localization support (partially) implemented, German (de) translation

### PR DESCRIPTION
**Pull request by jonnius**
localization support implemented except for measurements and units. I did not know how to achieve that. Maybe you know better ;)
I created the pot file with the following command: 
xgettext -k_ -kN_ -o po/modern-calc.pot app_header.js basic_calc_button_grid.js calculator_module.js calculus_history.js display.js extension.js message_view.js modern_calc.js prefs.js unit_converter_module.js utils.js --from-code=UTF-8
German (de) translation included

### CODE REVIEW

**Comment by kaer** [comment]
I wanted to support localization but I can't and didn't know how to use a
translator editor, I tried poeditor and others but things didn't worked as
wanted.

THANK YOU VERY MUCH by the work, now the extension will have localization
support.

I don't know how to use github to include the code, to be sincere I learn't
a bit of git because this extension. Is possible to include these changes
to a newer code?  because my local repo is v7 and the master is v6.

**Comment by jonnius** [comment]
Great to hear, that you want to implement it. If the github repository
is not up to date you can update it of course. I am not an expert, but i
would say, those steps will do the job:
1. cd /local/repository
2. git add <every> <single> <change> <file>
3. git commit -m "Message that explains the change shortly"
4. git push

And afterwards you can just merge my change on github. It may be that my
and your changes collide, but github will help you fix the conflicts.
Afterwards do "git pull" on your local repository to get it up to date
with the changes from github.

Could you think about a solution for the measurement and unit names?
You have very long lists of them, and some measurements having more than
one name. In other languages they might have less or even more names.
And you need a more generell solution for plural forms
(http://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html).

**Comment by kaer** [comment]
The code was updated yesterday, I know the commands  but I don't know how safe is to merge the code of master repo. I need learn about it, will read some documentation.

The localization of unit names it's simple, in next hours I'll post the code, but for a while I'm away my PC with GShel, can you test it for me.

**Comment by kaer** [comment]
I guess the localization of unit names may generate unexpected behaviors, I'll test the code first and later update the repo.

**Comment by kaer** [comment]
There is a way to add more translations to the pot file without loose the current ones?

I added more translations to my locale using a text editor and later compiled in poedit.

**Comment by jonnius** [comment]
As mentioned before, you can create it from files like mentioned above. If there are more strings that don't appear in the js files you can append them using a texteditor or you could create a file like po/strings.js with the following content, that you use additionally to create the pot file:

//Additional translatable Strings
_("String 1")
_("String 2")
_("String 3")

**Comment by kaer** [comment]
I did it, thanks again. check the file pt_BR.po because more strings were added and the units are translated too.

Do you know a function to get the msgid text from msgtr text (inverse of the function _() )?

**Comment by jonnius** [comment]
Great! Would be better to new entries to pot file (po template).

Don't know, but don't think so, for it is not unique. There could be multiples Strings translated by the same string in another language.

**Comment by kaer** [comment]
Right. I'd like to use expressions in other language than English for conversions.

e.g.:
- 100 metro > jarda

instead of
- 100 meter to yard

**Comment by jonnius** [comment]
I think, gettext is not the right way, if the localized text is needed for logical operations. Maybe you could use a file for units. Something with a syntax like that:

KEYWORD: LOCALIZED1, LOCALIZED2, LOCALIZED3, ...

in the spezific case it could be:

yard: jarda
meter: metro, metros

And the english one:

yard: yard, yards
meter: meter, metre, meters, metres

So you would need to recognize the language and then choose the the list and if it does not exist, you have the english one as fallback. Or you could always use the english one + the localized one, if exists.

What do you think about that idea?

**Comment by kaer** [comment]
I asked about gettext because would be easier than using another way. Your idea is nice, I'll do it. Thanks by the help.

**Comment by kaer** [comment]
I updated the code, the expression syntax now is 'X > Y'

**Comment by jonnius** [comment]
Don't you think, it would be better to have one unit list per language? Maybe stored in the locale/ll_LL folder? Maybe you could explain how to translate units in Readme, too.

**Comment by kaer** [comment]
You are right, the way I did can make conflicts between languages with different units with the same name. I'll work on it.

**Pull request merged**
